### ISSUE TITLE
[功能增强] 增加自动公招功能

### ISSUE THREAD

**Issue by simonkorl** [closure-studio/ReadMe#14]
可以在托管详情页面增加一个按钮，或是在挂机配置的选项中增加一个选项。

通过一个输入框输入你想使用的公招券的数量以及你想要使用的加急许可的数量来自动公招。

**Comment by fexli** [comment]
后端已存在设置：“保留公招券”和“是否招募支援机械机器人”，加急许可一般不视为挂机使用对象（自然冷却，公招加速仅为手动使用定制）需要 @jackjieYYY 添加设置api @skadiD 添加前端相关设置
