### ISSUE TITLE
托管账号密码都正确但是显示验证错误

### ISSUE THREAD

**Issue by Aisaka-t** [closure-studio/ReadMe#18]
交流群已经改为不允许任何人加入，不知道怎么联系管理员

**Comment by Aisaka-t** [comment]
![Screenshot_2022-07-30-14-02-57-311_com chrome beta](https://user-images.githubusercontent.com/60498116/181877092-93ce84ae-7622-4f96-95b2-336b27e4ec48.jpg)
一天之后变成这样了。。。

**Comment by 64luo** [comment]
我也遇到了这个问题不知道怎么弄，你现在解决了吗

**Comment by Aisaka-t** [comment]
> 我也遇到了这个问题不知道怎么弄，你现在解决了吗

没有解决，这几天每天都有试，但是没用，现在还是验证错误

**Comment by Aisaka-t** [comment]
刚刚试了试，好了，感谢各位可露希尔工作室大佬们的付出

**Comment by jackjieYYY** [comment]
新增人机验证功能，应该能改善该问题。

**Comment by skadiD** [comment]
done
