### ISSUE TITLE
账号托管登陆

### ISSUE THREAD

**Issue by linzxv** [closure-studio/ReadMe#19]
我十分确定账号密码都是正确的,但是登陆提示账号密码错误,服务器也没有选错  
![这是截图](https://s2.loli.net/2022/08/02/hGEP4t36WC7q9cB.jpg)

**Comment by skadiD** [comment]
参考 #20 需要完成验证码

**Comment by linzxv** [comment]
现在可以了,非常感谢!

**Comment by linzxv** [comment]
现在可以了,非常感谢!
