### ISSUE TITLE
登录出现新的问题

### ISSUE THREAD

**Issue by 64luo** [closure-studio/ReadMe#20]
在登录账号时需要手动刷新的时候点击刷新会一直转圈圈加载一直如此然后过一段时间就显示网页无响应，退出浏览器重新进入显示验证出错

**Comment by skadiD** [comment]
刚刚修复 
另外如果提示验证出错 需要重新执行登录操作 并且反复【手动刷新】列表 直到状态更新成【需要验证】
此时点击【需要验证】后即会弹出验证码 
通过验证码后 即会正常重新登录

**Comment by 64luo** [comment]
好的，已经登录上去了，谢谢各位大佬
