### ISSUE TITLE
[功能完善]能否增加自动作战重试、能否支持控制中枢不换班

### ISSUE THREAD

**Issue by yltx** [closure-studio/ReadMe#26]
现版本似乎只要代理失误就提示作战错误请联系管理员，为啥不能自动重试呢？
以及   能否支持控制中枢不换班？

**Comment by skadiD** [comment]
1.目前提示作战失败的条件是连续代理失误达到3次以上，并不是没有自动重试，功能请求不成立
2.当前版本暂不支持基建功能开关切换，如对自动基建换班有异议请补充说明
3.后续将更新通知BOT，代理失误时及时通知到位，敬请期待

**Comment by yltx** [comment]
> 1.目前提示作战失败的条件是连续代理失误达到3次以上，并不是没有自动重试，功能请求不成立 2.当前版本暂不支持基建功能开关切换，如对自动基建换班有异议请补充说明 3.后续将更新通知BOT，代理失误时及时通知到位，敬请期待

既然有自动重试那没事了  当我没说（

**Comment by jackjieYYY** [comment]
请再次观察日志，应该有作战失败 重新作战的 相关信息。同时可以观察作战截图回顾是哪个时间节点作战失败。
