### ISSUE TITLE
[功能请求] 全局自动重连配置

### ISSUE THREAD

**Issue by skadiD** [closure-studio/ReadMe#3]
考虑到部分用户有长期托管的需求，应该将全局配置改为单账号生效，
同时增加手动暂停 / 启动 托管功能

**Comment by jackjieYYY** [comment]
以下是我的理解
1. [长期托管] 即使后端服务器重启，该账号依然处于托管状态。
2. 添加暂停托管/恢复托管功能 [避免用户游玩肉鸽时被顶下线]
