### ISSUE TITLE
希望可以添加一个刷剿灭的功能

### ISSUE THREAD

**Issue by warfarinff0** [closure-studio/ReadMe#30]
能用跳过卡的剿灭就打，没有跳过卡就不打

**Comment by jackjieYYY** [comment]
请再次检查，closure-studio支持刷剿灭功能

**Comment by warfarinff0** [comment]
貌似没看到，难道要把最新的剿灭打一遍吗？

**Comment by jackjieYYY** [comment]
请检查日志

应该有类似的记录

[剿灭] 扫荡完成~ 进攻关卡："拉特兰：巧克力大街"，获得：1.2倍奖励[龙门币(250)] 常规掉落[初级作战记录(10)] 源石物资[合成玉(370)]，当前合成玉：1110/1800，当前剩余3理智

**Comment by fexli** [comment]
现在仅支持扫荡剿灭，不支持录像方式进攻剿灭（时间过长），请先检查账号剿灭地图中是否有能进行委托作战的剿灭关卡
