### ISSUE TITLE
希望复刻之前版本自动刷信赖功能

### ISSUE THREAD

**Issue by RsatoL** [closure-studio/ReadMe#31]
依稀记得之前1-7是可以自动刷信赖的

**Comment by jackjieYYY** [comment]
现在也可以。

摆上一队需要刷新信赖的编队，重新打一次1-7(切记蓝门前放盾)并更新录像即可

**Comment by RsatoL** [comment]
早期版本刷1-7时似乎可以自动替换未满信赖干员进入战斗，记忆混乱，现在必须要手动编队吗

**Comment by fexli** [comment]
目前看来牡蛎desu，可以手动换信赖干员打关卡保存代理录像再交给可露希尔。
