### ISSUE TITLE
RemoteArrangement：无法识别更好的排班

### ISSUE THREAD

**Issue by Qingmuc** [closure-studio/ReadMe#34]
控制中枢中已有阿米娅+三个“**异格者**”【进驻控制中枢时，控制中枢内每个**异格**干员可使控制中枢内所有干员心情每小时恢复+**0.05**】时，系统无法给出*最优解*（进驻一个无技能**异格**使心情每小时恢复+**0.15**）而选择*次解*（进驻一个“**S.W.E.E.P.**”【进驻控制中枢时，控制中枢内所有干员的心情每小时恢复+**0.05**】使心情每小时恢复+**0.05**）

**Comment by fexli** [comment]
已修复该问题，由模型设计缺陷引起，已修复，等待整合。
