### ISSUE TITLE
RemoteArrangement：无法识别更好的排班(2)

### ISSUE THREAD

**Issue by Qingmuc** [closure-studio/ReadMe#35]
### 在阅读这个Issue前，不妨了解一些 *基建-会客室-线索收集* 的一些知识。

> **最终加成百分比**是下述表格列出百分数的**加算**
> 干员在处于**注意力涣散**的情况下，依然会触发 **精英化 星级** 的加成
> | 宿舍氛围累计加成    |     | 进驻干员星级 |    | 进驻干员精英阶段 |     | 会客厅等级 |     | 非涣散加成 |
> |:-----------:|:---:|:------:|:---:|:--------:|:---:|:-----:|:---:|:-----:|
> | 条件          | 加成  | 条件     | 加成 | 条件       | 加成  | 条件    | 加成  | 5%    |
> | 0\-1999     | 0%  | 1\-3   | 0% | 0        | 0%  | 1     | 7%  |       |
> | 2000\-2999  | 5%  | 4      | 2% | 1        | 8%  | 2     | 9%  |资料引自|
> | 3000\-3999  | 10% | 5      | 4% | 2        | 16% | 3     | 11% |PRTS.WIKI|
> | 4000\-20000 | 15% | 6      | 5% |          |     |       |     |由本人进行排版|

根据以上数据，我们可以轻松算出：
一个 **精二** 的 **6★干员** 在**没有任何技能**的情况下，最终加成为（假设其他变量  “**宿舍氛围**”  “**会客室等级**”  均为满级）
**宿舍氛围加成15%**  +   **6★干员加成5%**  +  **精二加成16%**  +  **会客室等级加成11%**  +  **非涣散加成5%**  =  +**52%**
一个 **12F** 在技能[进驻会客室时，线索搜集速度+**20%**]的情况下，最终加成为：
**宿舍氛围加成15%**  +   **1\-3★干员加成0%**  +  **精零加成0%**  +  **会客室等级加成11%**  +  **非涣散加成5%**  +  **技能加成20%**  =  +**51%**

- 我们由此得出结论：任何一个精二的6★干员的效率加成都比12F要高，而目前RemoteArrangement的逻辑将12F仍列为高优先级，但诸如精二的红、践行者等高质量会客室干员优先级极低。
- 在此提出建议。

**Comment by Qingmuc** [comment]
哦对了，本Issue其实和 #34 还是有一定的联动的，上一个Issue中，进驻的“**S.W.E.E.P.**”就是本Issue中提到的高质量会客室干员红...

**Comment by fexli** [comment]
首先，很好的提问规范。
其次，所有排班计算规则都按照数据最优加成区域来计算，且控制中心优先级比会客室排班优先级更高，请悉知。
回答问题：
1、当计算加成效率时，已知(1)给出的表格中数据叠加均为加算（+%）；已知(2)在单会客室的情况下，`会客室等级`、`宿舍氛围加成`均为固定值，因此可知：在单会客室的前提下，可忽略`会客室等级`、`宿舍氛围加成`加成（非涣散同理），因此效率差距仅在`干员星级`、`干员精英化`以及`干员自身技能`
2、（为什么该账号里红不会被排到会客室）根据优先级计算条件，排班系统会优先对控制中心进行排班，在干员数量不足时会优先使用部分恢复心情（如S.W.E.E.P.）的干员，计算完成之后后续才会进行会客室的排班，假设在会客室排班之前已经将带有会客室BUFF的高星/精英化等级干员排班出去的话就不会对该干员再次计算排班。因此，请注意排版（或自身干员列表）中是否缺少（或较少）对应会客室效率提升BUFF类的干员。
3、（为什么其他六星没有被排到会客室）目前排班加速是根据优化器对目标干员进行筛选并进行差别排班（即：***在当前[或最后更新前]版本扩展效率无关的干员/无技能的干员/无效率的干员***会被筛选排除，仅留下***有技能/效率加成***的干员）很遗憾当时在优化时忽略了这部分根据干员自身等级/类型加成的效果，后续会进行修复并适配。
感谢您的反馈。
