### ISSUE TITLE
网页闪烁黑屏

### ISSUE THREAD

**Issue by 2111802370** [closure-studio/ReadMe#37]
进入网页后黑屏，刷新会闪烁一下但无法显示，之后再次网页黑屏

**Comment by wty1714611630** [comment]
![P2}M2}%15_71OVS%ZXUWAD9](https://user-images.githubusercontent.com/102363997/193577719-29ef26be-839d-4aef-ae37-d63a2007755b.png)

**Comment by skadiD** [comment]
目前该问题得以初步解决，如托管列表界面只存在【启动】【删除】按钮，烦请在用户交流群内联系 @jackjieYYY 修复个人账号数据
