### ISSUE TITLE
[基建]泡泡组提高贝娜优先级

### ISSUE THREAD

**Issue by joe-vettek** [closure-studio/ReadMe#39]
可露希尔似乎不怎么使用贝娜，且在我之前没有精二稀音的时候，偏向于使用蛇屠箱、黑角补充泡泡组。
![1667752487883.jpg](https://user-images.githubusercontent.com/82761814/200183811-ce9de8a8-90e9-4afe-b26c-92b88e2e3a2d.jpg)![1667752487873.jpg](https://user-images.githubusercontent.com/82761814/200183821-d1f607c1-cbd0-4735-89c3-e49398320205.jpg)

**Comment by joe-vettek** [comment]
补充宿舍情况：稀音和贝娜本轮换班之前都是满体力。进入制造站后初始扣除1点，现在均为23点。

**Comment by joe-vettek** [comment]
泡泡组中
稀音+12容量（初始+15%）=0.27
贝娜+17容量（-20%）=0.31
蛇屠箱+10容量（+10%）=0.20

红云组中
稀音+12容量（初始+15%）=0.39
贝娜+17容量（-20%）=0.14
蛇屠箱+10容量（+10%）=0.30

**Comment by fexli** [comment]
和`根据干员提供的制造站容量增加生产力`的bug一起修了
