### ISSUE TITLE
基建和信用商店 问题很大（）

### ISSUE THREAD

**Issue by Sakuma-Rei** [closure-studio/ReadMe#42]
![Screenshot_2022-12-07-15-59-36-112_com hypergryph](https://user-images.githubusercontent.com/55101422/206121844-f6b5f262-b475-4e5d-b9bb-b6c62c8152da.jpg)
信用默认买了加急许可 就 屏蔽一下加急许可和碳吧 最优肯定是买完sale然后按剩下按性价比买（
![Screenshot_2022-12-07-15-58-39-239_com hypergryph](https://user-images.githubusercontent.com/55101422/206122345-8a6945a6-c129-46cf-af88-a973a5df06b5.jpg)
基建问题很多（）比如线索不缺1给我排上了塞雷娅（）然后陈反而塞到了中枢 虽然有小老虎但 中枢放了夕用了絮雨但又没放迷迭香 没放爱丽丝 
![Screenshot_2022-12-07-15-58-28-953_com hypergryph](https://user-images.githubusercontent.com/55101422/206123095-18bc54c9-c3b0-49f6-add2-291b385bba05.jpg)
![Screenshot_2022-12-07-15-58-22-457_com hypergryph](https://user-images.githubusercontent.com/55101422/206123134-ae12c0a0-efae-4d59-aebb-f277e590900f.jpg)
jiu就是这个制造站 看着问题很大（）
![Screenshot_2022-12-07-15-58-26-198_com hypergryph](https://user-images.githubusercontent.com/55101422/206123241-87fc3ce6-4bd3-4ddf-a67c-ad71e7c05caa.jpg)
制造站只有这个略高于我之前的方案 我原来的排班制造站应该很难低于1（没游戏图x）
那就放点一图流截图吧（
![2022-12-07_161542](https://user-images.githubusercontent.com/55101422/206125258-80386973-44d4-47fc-9e9d-bfdc96300cb7.png)
宿舍默认塞了心情回复组（蹭信赖不知道会不会 暂时没考证（

**Comment by Sakuma-Rei** [comment]
未进驻就没放了 感觉没啥关联性 有的排过了也继续上班
![Screenshot_2022 12 07_16 40 41 337](https://user-images.githubusercontent.com/55101422/206130385-c50d16b8-eb0d-4716-9226-95917bcb9ee4.png)
![Screenshot_2022 12 07_16 40 46 686](https://user-images.githubusercontent.com/55101422/206130403-d00bb3f8-aef1-4639-b8e7-f5f6fa7aa4cc.png)
![Screenshot_2022 12 07_16 40 51 502](https://user-images.githubusercontent.com/55101422/206130415-d08e4612-ecd1-42d4-b6e5-5ea666e89278.png)
![Screenshot_2022 12 07_16 41 09 252](https://user-images.githubusercontent.com/55101422/206130421-a2aff37c-698e-4f33-8a51-a392abfa4234.png)
![Screenshot_2022 12 07_16 41 52 570](https://user-images.githubusercontent.com/55101422/206130429-b51bff3f-cb0c-4cd3-8e4a-b773a93aec65.png)
排班大概这样子？这是之后又换的（差不多是这种感觉 凯尔希去宿舍了暂时

**Comment by Sakuma-Rei** [comment]
具体效率有待考证（没拆分过夕令）好像也差不多 但是那个塞雷娅是真的没明白（

**Comment by jackjieYYY** [comment]
感谢您的反馈。

在设定上加急许可和碳是处于最低优先度的。图一暂时没看出任何问题。图一的家具零件和加急许可是因为其他高价值的物品买完了才进行购买。

基建问题待内部商议再进行答复

**Comment by fexli** [comment]
感谢您的反馈。
首先，对于信用商店购买楼上给出了部分解答，这里再详细说明一下，购买会综合考虑优惠和价格以及稀有度差异，信用商店作为公招加急许可`必不可缺`的一种`重要的`获取途径，会放在购买较后的位置考虑（而不会强制性忽略）当您的信用高于加急许可价格，且商店内无其他可购买的更优商品时就会进行购买操作，而不会不购买将信用保留到明日的商店。
其次，目前由于排班是通过贪心策略完成无法达到全局最优，且手动排班还未开放([~~~咕咕咕~~~](https://github.com/closure-studio/ReadMe/issues/32#issuecomment-1261623693))排班效率精度还没有达到最优，请谅解
最后，关于会客室的问题已经排查完成并修复，很快代码推送后就可以恢复。

**Comment by fexli** [comment]
然后顺手补充一下，目前

1. 至简组合
2. 发电站组合
3. 赤金生产线

这几个暂时还没有做（在赶ddl还没空）之后再去写啦，可能是这个引起的迷迭香没有被正确放入的奇奇怪怪的bug
