### ISSUE TITLE
近期战斗和信用商店仍存在的bug

### ISSUE THREAD

**Issue by Sakuma-Rei** [closure-studio/ReadMe#43]
![2022-12-10_085101](https://user-images.githubusercontent.com/55101422/206875815-379c6850-b2f6-4a76-9542-1de1556f3d52.png)
![2022-12-11_051652](https://user-images.githubusercontent.com/55101422/206875819-f0ab5756-11a7-4e38-b7b4-4431df386d5f.png)
最近两天战斗出现的bug 云端的不定时截图均未发现问题 应该是需要重启才能继续代理 同时希望可露希尔-账号信息详情页也能增设一个暂停重启的界面
![QQ图片20221211052259](https://user-images.githubusercontent.com/55101422/206875928-4bc1a9b1-360c-4a92-9b3d-db0812a02c95.jpg)
依旧是买了加急许可甚至不买招聘许可的问题 不管怎么说 以可露希尔的自动公招速度而言并不像会囤积招聘许可的样子 且作为一个不会一次性大量消耗招聘许可的刀客塔来说个人是从来不买加急并且有三百的自然积累 还是希望有直接屏蔽加急许可的选择空间

**Comment by jackjieYYY** [comment]
信用商店问题已修复
