### ISSUE TITLE
移动端app的两个意见

### ISSUE THREAD

**Issue by HarayamaRese** [closure-studio/ReadMe#47]
申请在移动端app中，公开招募获得高星干员时app内弹窗通知；
网页端不同log类型有不同颜色的语句高亮，希望移动端app内也更新这个内容；

**Comment by jackjieYYY** [comment]
该意见已转发

https://github.com/heyanLE/Closure/issues/1

https://github.com/joe-vettek/ClosureHelper/issues/1

**Comment by joe-vettek** [comment]
不知道何言大佬的那边怎么样，但是我这边是有处理的。五星和六星以黄色字体在日志中标出。
