### ISSUE TITLE
无法开始下一次自动代理

### ISSUE THREAD

**Issue by Mortalsaa** [closure-studio/ReadMe#49]
上一次代理正常进行结束后，没有下一次代理战斗何时开始的提示。之后只会定时更换基建不会定时清理理智。
![Uploading C557BB85-0069-4811-AAA7-3F797DFF3A64.png…]()

**Comment by Mortalsaa** [comment]
![Uploading 4AB1DA8B-0E54-4AB4-9C89-57D7AA6FB81F.png…]()

**Comment by jackjieYYY** [comment]
请发一下战斗日志的代码，只需一个即可

<html>
<body>


2023-03-19 16:08:18 | [幽岚v3] 战斗前检查通过，准备进攻 "CF-8" (co-931ea373-0e8e-45c2-6761-7029967ee2c4)
-- | --



</body>
</html>

**Comment by Mortalsaa** [comment]
co-d5000fc0-4899-cd7c-94c8-7a9598faebc2)

**Comment by Mortalsaa** [comment]
[幽岚v3] 战斗前检查通过，准备进攻 "1-7" (co-a33722bd-b4ec-1008-2906-4835fd6ee4d1)
所以出了什么问题

**Comment by jackjieYYY** [comment]
该问题已修复
