### ISSUE TITLE
希望能增加日志功能

### ISSUE THREAD

**Issue by SummerMoonxi** [closure-studio/ReadMe#5]
增加一个以月或者周为周期的日志功能，以方便查询

**Comment by fexli** [comment]
目前服务器的日志存储周期应该没有这么长的。目前已经实现了当次托管（即：从开启托管开始，到账号失败或服务器重启截止）的log存储，即将实装前端日志显示；另外我们正准备策划基于Bot的持久化消息通知，敬请期待。

**Comment by skadiD** [comment]
目前日志已上线 日志有效期为单次游戏账号登录
