### ISSUE TITLE
[Feature]: 增加战斗错误截图查询，以供自我检查战斗出错原因

### ISSUE THREAD

**Issue by CottonCandy2004** [closure-studio/ReadMe#52]
分离issue

              > 关于第一条自动作战，如果作战失败会有3次重试机会。如果还是失败若干小时候会重新登陆再进行尝试。

不好意思，请问一下战斗开始就出错是哪里有问题吗？
![Screenshot 2023-03-19 231259](https://user-images.githubusercontent.com/95153572/226185749-0afafed3-5a7c-4bf2-8a3e-64a9f2242439.png)
`co-46ee51b3-fcc8-8b07-bc90-40b11595a322`

_Originally posted by @CottonCandy2004 in https://github.com/closure-studio/ReadMe/issues/46#issuecomment-1475291067_

**Comment by jackjieYYY** [comment]
有几个大原因，网络问题，安卓或者游戏卡死问题，或者是无法3星通过。下个版本将会上传截图供用户回溯原因

**Comment by CottonCandy2004** [comment]
一开始就出错感觉是无法3星通过可能性不大，游戏卡死问题可能性更大点。亦或者只是游戏反应慢了点可小姐误以为卡死了之类的（我曾使用MAA+蓝叠模拟器的性能模式，进入战斗的时间长了点，MAA一直以为游戏崩溃）……

但还是感谢解答！
