### ISSUE TITLE
基建控制中枢排版

### ISSUE THREAD

**Issue by 385147** [closure-studio/ReadMe#53]
三异格者外加另外两异格的永动机
能不能别再把百嘉换成阿米娅了
![0C63A605-5E4F-4417-AAFC-466C4643AA59](https://user-images.githubusercontent.com/130836321/232209930-95b1217c-1493-470b-bbb0-b30d84cb1f60.png)

**Comment by fexli** [comment]
你好，很高兴收到基建反馈，但是由于基建最优规划设计核心目标“在一定范围内尽可能达到最高加成效率”，而“**阿米娅**”作为为数不多的能够在控制中枢跨房间对其他多个房间产生加成【进驻控制中枢时，所有贸易站订单效率+7%（同种效果取最高）】的干员，其优先级是远高于所谓“永动机组合”的SP心情组合的。（在基建排班时也会将低心情干员放入宿舍回复心情）因此无法将当前SP组合考虑为最优解。
