### ISSUE TITLE
关于自动使用信用购买材料功能

### ISSUE THREAD

**Issue by HarayamaRese** [closure-studio/ReadMe#55]
新增选项，选择是否自动使用信用购买材料，开了让可小姐自动买，关了自己上线买；
PS1：或使用信用购买材料之前，检查干员解锁进度中，坚雷是否已经全部聘用；
如果不是：自动购买坚雷（如果信用不够，继续攒信用）
如果是：自动购买材料
（来自一个在你站从8级挂到58级，坚雷还是2潜的白咕咕绯闻男友）

**Comment by jackjieYYY** [comment]
该要求属于小众需求。不在考虑范围内。谢谢您的提议。
