### ISSUE TITLE
希望能加新干员基建岗位

### ISSUE THREAD

**Issue by Annngg** [closure-studio/ReadMe#59]
![IMG_1180](https://github.com/closure-studio/ReadMe/assets/141302049/dea7a3ae-0a21-4770-8ab5-21d1f6236d2d)
新干员这样搭配基建效率能到1.12 可小姐似乎不会这样搭配 希望能加一下

**Comment by Criogaid** [comment]
@fexli

**Comment by fexli** [comment]
会在最近完成更新

**Comment by Annngg** [comment]
![IMG_4553](https://github.com/closure-studio/ReadMe/assets/141302049/a2324efd-affb-42f0-bc54-e753748c76bf)
![IMG_4551](https://github.com/closure-studio/ReadMe/assets/141302049/94159088-f708-43fc-a8a0-2c563e634f3a)
![IMG_4555](https://github.com/closure-studio/ReadMe/assets/141302049/99d211cb-3e53-448d-a982-f5facc2fafc5)
![IMG_4549](https://github.com/closure-studio/ReadMe/assets/141302049/bd662abf-3208-49b3-a59a-dfc0eefc735d)
![IMG_4550](https://github.com/closure-studio/ReadMe/assets/141302049/9bbf8ba8-ec9d-4601-bfb5-3bfe86072bec)

 目前可小姐排班似乎会把中枢黑角夜刀组合拆开，导致黑角精二技能跟阿米娅技能重复，效率不能最大化，希望改成黑角夜刀捆绑中枢，贸易站放入艾露猫，效率可达到48%，另外精一孑无法简单跟能天使等人搭配，如何解决这种问题

**Comment by Annngg** [comment]
> 会在最近完成更新

![IMG_4553](https://github.com/closure-studio/ReadMe/assets/141302049/a2324efd-affb-42f0-bc54-e753748c76bf)
![IMG_4551](https://github.com/closure-studio/ReadMe/assets/141302049/94159088-f708-43fc-a8a0-2c563e634f3a)
![IMG_4555](https://github.com/closure-studio/ReadMe/assets/141302049/99d211cb-3e53-448d-a982-f5facc2fafc5)
![IMG_4549](https://github.com/closure-studio/ReadMe/assets/141302049/bd662abf-3208-49b3-a59a-dfc0eefc735d)
![IMG_4550](https://github.com/closure-studio/ReadMe/assets/141302049/9bbf8ba8-ec9d-4601-bfb5-3bfe86072bec)

 目前可小姐排班似乎会把中枢黑角夜刀组合拆开，导致黑角精二技能跟阿米娅技能重复，效率不能最大化，希望改成黑角夜刀捆绑中枢，贸易站放入艾露猫，效率可达到48%，另外精一孑无法简单跟能天使等人搭配，如何解决这种问题
