### ISSUE TITLE
账号无法登陆

### ISSUE THREAD

**Issue by lenmon1231** [closure-studio/ReadMe#61]
你好，可露希尔的账号登不进去。现在用小号申请交流群也进不去（原本在群的大号被腾讯封了）

**Comment by lenmon1231** [comment]
> GitHub上传图片显示错误。QQ也申请你的好友了。

现在用的小号Q192844395，可能会被腾讯过滤。

**Comment by jackjieYYY** [comment]
目前已关闭网页端的使用。如果急需使用请自行对接API

https://github.com/closure-studio/ReadMe/blob/main/arknightsAPIDoc.md

**Comment by eden000208** [comment]
> 网页端于十月一日关闭。如果急需使用请自行对接API
> 
> 
> 
> https://github.com/closure-studio/ReadMe/blob/main/arknightsAPIDoc.md

注册api返回无效，之前的账号是被清空了吗？

**Comment by jackjieYYY** [comment]
https://closurestudio2.4everland.app/

**Comment by jackjieYYY** [comment]
> > 网页端于十月一日关闭。如果急需使用请自行对接API
> > https://github.com/closure-studio/ReadMe/blob/main/arknightsAPIDoc.md
> 
> 注册api返回无效，之前的账号是被清空了吗？

https://closurestudio2.4everland.app/

**Comment by eden000208** [comment]
> > > 网页端于十月一日关闭。如果急需使用请自行对接API
> 
> > > https://github.com/closure-studio/ReadMe/blob/main/arknightsAPIDoc.md
> 
> > 
> 
> > 注册api返回无效，之前的账号是被清空了吗？
> 
> 
> 
> https://closurestudio2.4everland.app/

注册api还是无反应 是没开放吗？
