### ISSUE TITLE
请求多开些材料关卡

### ISSUE THREAD

**Issue by mustarkawaii** [closure-studio/ReadMe#7]
可以开个扭转醇（6-11）、炽合金（s3-6）、凝胶（s4-10）吗？可露希尔的代打支持的材料有点少...感谢开发团队了！！！

**Comment by fexli** [comment]
需求与 #4 相同，目前后端已完成关卡开放逻辑规划，后续关卡添加敬请期待。

**Comment by jackjieYYY** [comment]
已添加

06/07/2022
